In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/hotel_bookings_clean.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city,lead_time_group,special_requests_group
0,Resort Hotel - Chandigarh,0,342,2024,July,30,27,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2024-07-27 22:16:40.916332324,Chandigarh,181-365 dni,0
1,Resort Hotel - Mumbai,0,737,2024,April,17,28,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2024-04-28 21:56:21.507509066,Mumbai,365+ dni,0
2,Resort Hotel - Delhi,0,7,2024,September,37,10,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2024-09-10 03:46:25.734029096,Delhi,0-7 dni,0
3,Resort Hotel - Kolkata,0,13,2024,August,33,14,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2024-08-14 18:07:10.049669568,Kolkata,8-30 dni,0
4,Resort Hotel - Lucknow,0,14,2024,September,37,14,0,2,2,...,0,Transient,98.0,0,1,Check-Out,2024-09-14 14:27:32.473846000,Lucknow,8-30 dni,1

In [2]:
df.shape

(118898, 34)

Na podstawie istniejących zmiennych utworzone zostaną nowe zmienne, które ułatwią analizę zależności pomiędzy cechami rezerwacji a jej anulowaniem.

In [3]:
df["lead_time_group"] = pd.cut(
    df["lead_time"],
    bins=[-1, 7, 30, 90, 180, 365, float("inf")],
    labels=["0-7 dni", "8-30 dni", "31-90 dni", "91-180 dni", "181-365 dni", "365+ dni"]
)

In [4]:
df["lead_time_group"].value_counts().sort_index()

lead_time_group
0-7 dni        19424
8-30 dni       18889
31-90 dni      29516
91-180 dni     26413
181-365 dni    21508
365+ dni        3148
Name: count, dtype: int64

In [5]:
df[["lead_time", "lead_time_group"]].head(10)

   lead_time lead_time_group
0        342     181-365 dni
1        737        365+ dni
2          7         0-7 dni
3         13        8-30 dni
4         14        8-30 dni
5         14        8-30 dni
6          0         0-7 dni
7          9        8-30 dni
8         85       31-90 dni
9         75       31-90 dni

In [6]:
df["lead_time_group"].isna().sum()

np.int64(0)

### Grupowanie liczby specjalnych życzeń

Na podstawie zmiennej `total_of_special_requests` utworzona zostanie nowa zmienna `special_requests_group`, która grupuje rezerwacje według liczby specjalnych życzeń klienta.

In [7]:
df["special_requests_group"] = pd.cut(
    df["total_of_special_requests"],
    bins=[-1, 0, 1, 2, 3, float("inf")],
    labels=["0", "1", "2", "3", "4+"]
)

In [8]:
df["special_requests_group"].value_counts().sort_index()

special_requests_group
0     69991
1     33121
2     12922
3      2487
4+      377
Name: count, dtype: int64

In [12]:
df.to_csv("../data/hotel_bookings_transformed.csv", index=False)

In [13]:
import os

os.listdir()

['hotel_bookings_transformed.csv',
 '02_transformacja.ipynb',
 '01_czyszczenie.ipynb',
 '.ipynb_checkpoints']

In [14]:
import os

os.listdir("../data")

['hotel_bookings_clean.csv',
 'hotel_bookings_updated_2024.csv',
 'hotel_bookings_transformed.csv',
 '.ipynb_checkpoints']